local _, ns = ...

-- ===========================================================================
-- goals/catalog_professions.lua  ·  profession Knowledge-Point goals (generated)
--
-- Two goals per profession per expansion (The War Within + Midnight, 11
-- professions each = 44 goals): a "One-Time ... Treasures" goal (world
-- treasures + research books + first-time gathers, no resets) and a
-- "Weekly ... KP" goal (treatise + work-order quest + gathered drops +
-- catch-up currency, resets weekly). Every Knowledge-Point source is a quest
-- completion flag, so steps are `flag` (single) / `group` of flags (any-of
-- weekly quest, count-each gathered drops); the catch-up is a `currency` cap
-- step. Darkmoon Faire sources are omitted in v1 (no "Faire is up" gate).
--
-- `require = { profession = <base skillLineID> }` gates each goal to characters
-- that know the profession. The base ID (171/164/333/...) is what
-- GetProfessionInfo's 7th return yields (the substrate/require match key), so
-- TWW and Midnight share a require per profession -- expansion can't be
-- distinguished from that number, accepted per the metadata-doc decision.
--
-- GENERATED, not hand-edited: the quest/item IDs are mechanically extracted, so
-- regenerate rather than editing in place (IDs shift with each game patch).
-- ===========================================================================

ns.Goals = ns.Goals or {}
local ProfessionCatalog = {}
ns.Goals.ProfessionCatalog = ProfessionCatalog

-- Flag-leaf list for group steps: { { evaluator = "flag", params = { quest = id } }, ... }
local function flags(ids)
	local of = {}
	for i = 1, #ids do of[i] = { evaluator = "flag", params = { quest = ids[i] } } end
	return of
end

-- Fresh tables per call (the catalog contract); appended to Catalog.entries().
function ProfessionCatalog.entries()
	return {
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-alchemy-midnight", rev = 1,
				name = "One-Time Alchemy Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Alchemy in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_alchemy",
				scope = "perchar",
				require = { profession = 171 },
				steps = {
					{ label = "[item=238536] (+3 KP)", evaluator = "flag", params = { quest = 89115 } },
					{ label = "[item=238538] (+3 KP)", evaluator = "flag", params = { quest = 89117 } },
					{ label = "[item=238532] (+3 KP)", evaluator = "flag", params = { quest = 89111 } },
					{ label = "[item=238535] (+3 KP)", evaluator = "flag", params = { quest = 89114 } },
					{ label = "[item=238537] (+3 KP)", evaluator = "flag", params = { quest = 89116 } },
					{ label = "[item=238534] (+3 KP)", evaluator = "flag", params = { quest = 89113 } },
					{ label = "[item=238539] (+3 KP)", evaluator = "flag", params = { quest = 89118 } },
					{ label = "[item=238533] (+3 KP)", evaluator = "flag", params = { quest = 89112 } },
					{ label = "[item=262645] (+10 KP)", evaluator = "flag", params = { quest = 93794 }, note = "Unlock: Renown 9; 75x [currency=3256]; 750x [currency=3316]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-alchemy-midnight", rev = 1,
				name = "Weekly Alchemy Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Alchemy in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_alchemy",
				scope = "perchar",
				require = { profession = 171 },
				steps = {
					{ label = "[item=245755] (+1 KP)", evaluator = "flag", params = { quest = 95127 }, resets = "weekly" },
					{ label = "[item=263454] (+1 KP)", evaluator = "flag", params = { quest = 93690 }, resets = "weekly" },
					{ label = "[item=259188] (+1 KP)", evaluator = "flag", params = { quest = 93528 }, resets = "weekly" },
					{ label = "[item=259189] (+1 KP)", evaluator = "flag", params = { quest = 93529 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3189, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-blacksmithing-midnight", rev = 1,
				name = "One-Time Blacksmithing Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Blacksmithing in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_blacksmithing",
				scope = "perchar",
				require = { profession = 164 },
				steps = {
					{ label = "[item=238540] (+3 KP)", evaluator = "flag", params = { quest = 89177 } },
					{ label = "[item=238543] (+3 KP)", evaluator = "flag", params = { quest = 89180 } },
					{ label = "[item=238546] (+3 KP)", evaluator = "flag", params = { quest = 89183 } },
					{ label = "[item=238547] (+3 KP)", evaluator = "flag", params = { quest = 89184 } },
					{ label = "[item=238541] (+3 KP)", evaluator = "flag", params = { quest = 89178 } },
					{ label = "[item=238542] (+3 KP)", evaluator = "flag", params = { quest = 89179 } },
					{ label = "[item=238545] (+3 KP)", evaluator = "flag", params = { quest = 89182 } },
					{ label = "[item=238544] (+3 KP)", evaluator = "flag", params = { quest = 89181 } },
					{ label = "[item=262644] (+10 KP)", evaluator = "flag", params = { quest = 93795 }, note = "Unlock: Renown 9; 75x [currency=3257]; 750x [currency=3316]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-blacksmithing-midnight", rev = 1,
				name = "Weekly Blacksmithing Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Blacksmithing in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_blacksmithing",
				scope = "perchar",
				require = { profession = 164 },
				steps = {
					{ label = "[item=245763] (+1 KP)", evaluator = "flag", params = { quest = 95128 }, resets = "weekly" },
					{ label = "[item=263455] (+2 KP)", evaluator = "flag", params = { quest = 93691 }, resets = "weekly" },
					{ label = "[item=259190] (+2 KP)", evaluator = "flag", params = { quest = 93530 }, resets = "weekly" },
					{ label = "[item=259191] (+2 KP)", evaluator = "flag", params = { quest = 93531 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3199, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-enchanting-midnight", rev = 1,
				name = "One-Time Enchanting Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Enchanting in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_enchanting",
				scope = "perchar",
				require = { profession = 333 },
				steps = {
					{ label = "[item=238551] (+3 KP)", evaluator = "flag", params = { quest = 89103 } },
					{ label = "[item=238555] (+3 KP)", evaluator = "flag", params = { quest = 89107 } },
					{ label = "[item=238549] (+3 KP)", evaluator = "flag", params = { quest = 89101 } },
					{ label = "[item=238554] (+3 KP)", evaluator = "flag", params = { quest = 89106 } },
					{ label = "[item=238548] (+3 KP)", evaluator = "flag", params = { quest = 89100 } },
					{ label = "[item=238552] (+3 KP)", evaluator = "flag", params = { quest = 89104 } },
					{ label = "[item=238553] (+3 KP)", evaluator = "flag", params = { quest = 89105 } },
					{ label = "[item=238550] (+3 KP)", evaluator = "flag", params = { quest = 89102 } },
					{ label = "[item=257600] (+10 KP)", evaluator = "flag", params = { quest = 92374 }, note = "Unlock: Renown 6; 75x [currency=3258]; 750x [currency=3316]" },
					{ label = "[item=250445] (+10 KP)", evaluator = "flag", params = { quest = 92186 }, note = "Unlock: 1600x [currency=3377]; 75x [currency=3258]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-enchanting-midnight", rev = 1,
				name = "Weekly Enchanting Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Enchanting in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_enchanting",
				scope = "perchar",
				require = { profession = 333 },
				steps = {
					{ label = "[item=245759] (+1 KP)", evaluator = "flag", params = { quest = 95129 }, resets = "weekly" },
					{ label = "[item=263464] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({93699, 93698, 93697}) }, resets = "weekly" },
					{ label = "[item=267654] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({95048, 95049, 95050, 95051, 95052}) }, resets = "weekly" },
					{ label = "[item=267655] (+4 KP)", evaluator = "flag", params = { quest = 95053 }, resets = "weekly" },
					{ label = "[item=259192] (+2 KP)", evaluator = "flag", params = { quest = 93532 }, resets = "weekly" },
					{ label = "[item=259193] (+2 KP)", evaluator = "flag", params = { quest = 93533 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3198, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-engineering-midnight", rev = 1,
				name = "One-Time Engineering Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Engineering in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_engineering",
				scope = "perchar",
				require = { profession = 202 },
				steps = {
					{ label = "[item=238556] (+3 KP)", evaluator = "flag", params = { quest = 89133 } },
					{ label = "[item=238562] (+3 KP)", evaluator = "flag", params = { quest = 89139 } },
					{ label = "[item=238558] (+3 KP)", evaluator = "flag", params = { quest = 89135 } },
					{ label = "[item=238563] (+3 KP)", evaluator = "flag", params = { quest = 89140 } },
					{ label = "[item=238561] (+3 KP)", evaluator = "flag", params = { quest = 89138 } },
					{ label = "[item=238559] (+3 KP)", evaluator = "flag", params = { quest = 89136 } },
					{ label = "[item=238560] (+3 KP)", evaluator = "flag", params = { quest = 89137 } },
					{ label = "[item=238557] (+3 KP)", evaluator = "flag", params = { quest = 89134 } },
					{ label = "[item=262646] (+10 KP)", evaluator = "flag", params = { quest = 93796 }, note = "Unlock: Renown 9; 75x [currency=3259]; 750x [currency=3316]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-engineering-midnight", rev = 1,
				name = "Weekly Engineering Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Engineering in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_engineering",
				scope = "perchar",
				require = { profession = 202 },
				steps = {
					{ label = "[item=245809] (+1 KP)", evaluator = "flag", params = { quest = 95138 }, resets = "weekly" },
					{ label = "[item=263456] (+1 KP)", evaluator = "flag", params = { quest = 93692 }, resets = "weekly" },
					{ label = "[item=259194] (+1 KP)", evaluator = "flag", params = { quest = 93534 }, resets = "weekly" },
					{ label = "[item=259195] (+1 KP)", evaluator = "flag", params = { quest = 93535 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3197, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-herbalism-midnight", rev = 1,
				name = "One-Time Herbalism Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Herbalism in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_herbalism",
				scope = "perchar",
				require = { profession = 182 },
				steps = {
					{ label = "[item=238470] (+3 KP)", evaluator = "flag", params = { quest = 89160 } },
					{ label = "[item=238472] (+3 KP)", evaluator = "flag", params = { quest = 89158 } },
					{ label = "[item=238469] (+3 KP)", evaluator = "flag", params = { quest = 89161 } },
					{ label = "[item=238473] (+3 KP)", evaluator = "flag", params = { quest = 89157 } },
					{ label = "[item=238468] (+3 KP)", evaluator = "flag", params = { quest = 89162 } },
					{ label = "[item=238471] (+3 KP)", evaluator = "flag", params = { quest = 89159 } },
					{ label = "[item=238475] (+3 KP)", evaluator = "flag", params = { quest = 89155 } },
					{ label = "[item=238474] (+3 KP)", evaluator = "flag", params = { quest = 89156 } },
					{ label = "[item=258410] (+10 KP)", evaluator = "flag", params = { quest = 93411 }, note = "Unlock: Renown 6; 75x [currency=3260]; 750x [currency=3316]" },
					{ label = "[item=250443] (+10 KP)", evaluator = "flag", params = { quest = 92174 }, note = "Unlock: 1600x [currency=3377]; 75x [currency=3260]" },
					{ label = "Learn all first-time gather recipes (+1 KP each, 30 recipes)", evaluator = "group", params = { need = 30, of = flags({87747, 87741, 87749, 87743, 87755, 87737, 87731, 87748, 87742, 87754, 87736, 87730, 87753, 87751, 87745, 87757, 87739, 87733, 87735, 87729, 87752, 87746, 87758, 87740, 87734, 87750, 87744, 87756, 87738, 87732}) } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-herbalism-midnight", rev = 1,
				name = "Weekly Herbalism Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Herbalism in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_herbalism",
				scope = "perchar",
				require = { profession = 182 },
				steps = {
					{ label = "[item=245761] (+1 KP)", evaluator = "flag", params = { quest = 95130 }, resets = "weekly" },
					{ label = "[item=263462] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({93700, 93701, 93702, 93703, 93704}) }, resets = "weekly" },
					{ label = "[item=238465] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({81425, 81426, 81427, 81428, 81429}) }, resets = "weekly" },
					{ label = "[item=238466] (+4 KP)", evaluator = "flag", params = { quest = 81430 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3196, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-inscription-midnight", rev = 1,
				name = "One-Time Inscription Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Inscription in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_inscription",
				scope = "perchar",
				require = { profession = 773 },
				steps = {
					{ label = "[item=238578] (+3 KP)", evaluator = "flag", params = { quest = 89073 } },
					{ label = "[item=238579] (+3 KP)", evaluator = "flag", params = { quest = 89074 } },
					{ label = "[item=238574] (+3 KP)", evaluator = "flag", params = { quest = 89069 } },
					{ label = "[item=238577] (+3 KP)", evaluator = "flag", params = { quest = 89072 } },
					{ label = "[item=238573] (+3 KP)", evaluator = "flag", params = { quest = 89068 } },
					{ label = "[item=238575] (+3 KP)", evaluator = "flag", params = { quest = 89070 } },
					{ label = "[item=238576] (+3 KP)", evaluator = "flag", params = { quest = 89071 } },
					{ label = "[item=238572] (+3 KP)", evaluator = "flag", params = { quest = 89067 } },
					{ label = "[item=258411] (+10 KP)", evaluator = "flag", params = { quest = 93412 }, note = "Unlock: Renown 6; 75x [currency=3261]; 750x [currency=3316]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-inscription-midnight", rev = 1,
				name = "Weekly Inscription Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Inscription in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_inscription",
				scope = "perchar",
				require = { profession = 773 },
				steps = {
					{ label = "[item=245757] (+1 KP)", evaluator = "flag", params = { quest = 95131 }, resets = "weekly" },
					{ label = "[item=263457] (+4 KP)", evaluator = "flag", params = { quest = 93693 }, resets = "weekly" },
					{ label = "[item=259196] (+2 KP)", evaluator = "flag", params = { quest = 93536 }, resets = "weekly" },
					{ label = "[item=259197] (+2 KP)", evaluator = "flag", params = { quest = 93537 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3195, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-jewelcrafting-midnight", rev = 1,
				name = "One-Time Jewelcrafting Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Jewelcrafting in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_jewelcrafting",
				scope = "perchar",
				require = { profession = 755 },
				steps = {
					{ label = "[item=238580] (+3 KP)", evaluator = "flag", params = { quest = 89122 } },
					{ label = "[item=238582] (+3 KP)", evaluator = "flag", params = { quest = 89124 } },
					{ label = "[item=238585] (+3 KP)", evaluator = "flag", params = { quest = 89127 } },
					{ label = "[item=238583] (+3 KP)", evaluator = "flag", params = { quest = 89125 } },
					{ label = "[item=238587] (+3 KP)", evaluator = "flag", params = { quest = 89129 } },
					{ label = "[item=238581] (+3 KP)", evaluator = "flag", params = { quest = 89123 } },
					{ label = "[item=238584] (+3 KP)", evaluator = "flag", params = { quest = 89126 } },
					{ label = "[item=238586] (+3 KP)", evaluator = "flag", params = { quest = 89128 } },
					{ label = "[item=257599] (+10 KP)", evaluator = "flag", params = { quest = 93222 }, note = "Unlock: Renown 6; 75x [currency=3262]; 750x [currency=3316]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-jewelcrafting-midnight", rev = 1,
				name = "Weekly Jewelcrafting Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Jewelcrafting in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_jewelcrafting",
				scope = "perchar",
				require = { profession = 755 },
				steps = {
					{ label = "[item=245760] (+1 KP)", evaluator = "flag", params = { quest = 95133 }, resets = "weekly" },
					{ label = "[item=263458] (+3 KP)", evaluator = "flag", params = { quest = 93694 }, resets = "weekly" },
					{ label = "[item=259199] (+2 KP)", evaluator = "flag", params = { quest = 93539 }, resets = "weekly" },
					{ label = "[item=259198] (+2 KP)", evaluator = "flag", params = { quest = 93538 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3194, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-leatherworking-midnight", rev = 1,
				name = "One-Time Leatherworking Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Leatherworking in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_leatherworking",
				scope = "perchar",
				require = { profession = 165 },
				steps = {
					{ label = "[item=238595] (+3 KP)", evaluator = "flag", params = { quest = 89096 } },
					{ label = "[item=238588] (+3 KP)", evaluator = "flag", params = { quest = 89089 } },
					{ label = "[item=238590] (+3 KP)", evaluator = "flag", params = { quest = 89091 } },
					{ label = "[item=238591] (+3 KP)", evaluator = "flag", params = { quest = 89092 } },
					{ label = "[item=238593] (+3 KP)", evaluator = "flag", params = { quest = 89094 } },
					{ label = "[item=238594] (+3 KP)", evaluator = "flag", params = { quest = 89095 } },
					{ label = "[item=238589] (+3 KP)", evaluator = "flag", params = { quest = 89090 } },
					{ label = "[item=238592] (+3 KP)", evaluator = "flag", params = { quest = 89093 } },
					{ label = "[item=250922] (+10 KP)", evaluator = "flag", params = { quest = 92371 }, note = "Unlock: Renown 6; 75x [currency=3263]; 750x [currency=3316]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-leatherworking-midnight", rev = 1,
				name = "Weekly Leatherworking Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Leatherworking in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_leatherworking",
				scope = "perchar",
				require = { profession = 165 },
				steps = {
					{ label = "[item=245758] (+1 KP)", evaluator = "flag", params = { quest = 95134 }, resets = "weekly" },
					{ label = "[item=263459] (+2 KP)", evaluator = "flag", params = { quest = 93695 }, resets = "weekly" },
					{ label = "[item=259200] (+2 KP)", evaluator = "flag", params = { quest = 93540 }, resets = "weekly" },
					{ label = "[item=259201] (+2 KP)", evaluator = "flag", params = { quest = 93541 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3193, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-mining-midnight", rev = 1,
				name = "One-Time Mining Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Mining in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_mining",
				scope = "perchar",
				require = { profession = 186 },
				steps = {
					{ label = "[item=238599] (+3 KP)", evaluator = "flag", params = { quest = 89147 } },
					{ label = "[item=238597] (+3 KP)", evaluator = "flag", params = { quest = 89145 } },
					{ label = "[item=238601] (+3 KP)", evaluator = "flag", params = { quest = 89149 } },
					{ label = "[item=238603] (+3 KP)", evaluator = "flag", params = { quest = 89151 } },
					{ label = "[item=238602] (+3 KP)", evaluator = "flag", params = { quest = 89150 } },
					{ label = "[item=238596] (+3 KP)", evaluator = "flag", params = { quest = 89144 } },
					{ label = "[item=238598] (+3 KP)", evaluator = "flag", params = { quest = 89146 } },
					{ label = "[item=238600] (+3 KP)", evaluator = "flag", params = { quest = 89148 } },
					{ label = "[item=250924] (+10 KP)", evaluator = "flag", params = { quest = 92372 }, note = "Unlock: Renown 6; 75x [currency=3264]; 750x [currency=3316]" },
					{ label = "[item=250444] (+10 KP)", evaluator = "flag", params = { quest = 92187 }, note = "Unlock: 1600x [currency=3377]; 75x [currency=3264]" },
					{ label = "Learn all first-time gather recipes (+1 KP each, 21 recipes)", evaluator = "group", params = { need = 21, of = flags({88471, 88466, 88484, 88487, 88488, 88490, 88479, 88469, 88475, 88480, 88491, 88476, 88478, 88477, 88481, 88465, 88463, 88470, 88472, 88486, 88485}) } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-mining-midnight", rev = 1,
				name = "Weekly Mining Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Mining in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_mining",
				scope = "perchar",
				require = { profession = 186 },
				steps = {
					{ label = "[item=245762] (+1 KP)", evaluator = "flag", params = { quest = 95135 }, resets = "weekly" },
					{ label = "[item=263463] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({93705, 93706, 93707, 93708, 93709}) }, resets = "weekly" },
					{ label = "[item=237496] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({88673, 88674, 88675, 88676, 88677}) }, resets = "weekly" },
					{ label = "[item=237506] (+3 KP)", evaluator = "flag", params = { quest = 88678 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3192, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-skinning-midnight", rev = 1,
				name = "One-Time Skinning Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Skinning in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_skinning",
				scope = "perchar",
				require = { profession = 393 },
				steps = {
					{ label = "[item=238633] (+3 KP)", evaluator = "flag", params = { quest = 89171 } },
					{ label = "[item=238635] (+3 KP)", evaluator = "flag", params = { quest = 89173 } },
					{ label = "[item=238632] (+3 KP)", evaluator = "flag", params = { quest = 89170 } },
					{ label = "[item=238634] (+3 KP)", evaluator = "flag", params = { quest = 89172 } },
					{ label = "[item=238629] (+3 KP)", evaluator = "flag", params = { quest = 89167 } },
					{ label = "[item=238628] (+3 KP)", evaluator = "flag", params = { quest = 89166 } },
					{ label = "[item=238630] (+3 KP)", evaluator = "flag", params = { quest = 89168 } },
					{ label = "[item=238631] (+3 KP)", evaluator = "flag", params = { quest = 89169 } },
					{ label = "[item=250923] (+10 KP)", evaluator = "flag", params = { quest = 92373 }, note = "Unlock: Renown 6; 75x [currency=3265]; 750x [currency=3316]" },
					{ label = "[item=250360] (+10 KP)", evaluator = "flag", params = { quest = 92188 }, note = "Unlock: 1600x [currency=3377]; 75x [currency=3265]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-skinning-midnight", rev = 1,
				name = "Weekly Skinning Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Skinning in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_skinning",
				scope = "perchar",
				require = { profession = 393 },
				steps = {
					{ label = "[item=245828] (+1 KP)", evaluator = "flag", params = { quest = 95136 }, resets = "weekly" },
					{ label = "[item=263461] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({93710, 93711, 93712, 93713, 93714}) }, resets = "weekly" },
					{ label = "[item=238625] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({88534, 88549, 88536, 88537, 88530}) }, resets = "weekly" },
					{ label = "[item=238626] (+3 KP)", evaluator = "flag", params = { quest = 88529 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3191, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-tailoring-midnight", rev = 1,
				name = "One-Time Tailoring Midnight Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Tailoring in Midnight -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_tailoring",
				scope = "perchar",
				require = { profession = 197 },
				steps = {
					{ label = "[item=238613] (+3 KP)", evaluator = "flag", params = { quest = 89079 } },
					{ label = "[item=238618] (+3 KP)", evaluator = "flag", params = { quest = 89084 } },
					{ label = "[item=238614] (+3 KP)", evaluator = "flag", params = { quest = 89080 } },
					{ label = "[item=238619] (+3 KP)", evaluator = "flag", params = { quest = 89085 } },
					{ label = "[item=238612] (+3 KP)", evaluator = "flag", params = { quest = 89078 } },
					{ label = "[item=238615] (+3 KP)", evaluator = "flag", params = { quest = 89081 } },
					{ label = "[item=238616] (+3 KP)", evaluator = "flag", params = { quest = 89082 } },
					{ label = "[item=238617] (+3 KP)", evaluator = "flag", params = { quest = 89083 } },
					{ label = "[item=257601] (+10 KP)", evaluator = "flag", params = { quest = 93201 }, note = "Unlock: Renown 6; 75x [currency=3266]; 750x [currency=3316]" },
				},
			},
		},
		{
			bucket = "professions", tag = "Midnight",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-tailoring-midnight", rev = 1,
				name = "Weekly Tailoring Midnight KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Tailoring in Midnight -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_tailoring",
				scope = "perchar",
				require = { profession = 197 },
				steps = {
					{ label = "[item=245756] (+1 KP)", evaluator = "flag", params = { quest = 95137 }, resets = "weekly" },
					{ label = "[item=263460] (+2 KP)", evaluator = "flag", params = { quest = 93696 }, resets = "weekly" },
					{ label = "[item=259202] (+2 KP)", evaluator = "flag", params = { quest = 93542 }, resets = "weekly" },
					{ label = "[item=259203] (+2 KP)", evaluator = "flag", params = { quest = 93543 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3190, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-alchemy-tww", rev = 1,
				name = "One-Time Alchemy The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Alchemy in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_alchemy",
				scope = "perchar",
				require = { profession = 171 },
				steps = {
					{ label = "[item=226265] (+3 KP)", evaluator = "flag", params = { quest = 83840 } },
					{ label = "[item=226266] (+3 KP)", evaluator = "flag", params = { quest = 83841 } },
					{ label = "[item=226267] (+3 KP)", evaluator = "flag", params = { quest = 83842 } },
					{ label = "[item=226268] (+3 KP)", evaluator = "flag", params = { quest = 83843 } },
					{ label = "[item=226269] (+3 KP)", evaluator = "flag", params = { quest = 83844 } },
					{ label = "[item=226270] (+3 KP)", evaluator = "flag", params = { quest = 83845 } },
					{ label = "[item=226271] (+3 KP)", evaluator = "flag", params = { quest = 83846 } },
					{ label = "[item=226272] (+3 KP)", evaluator = "flag", params = { quest = 83847 } },
					{ label = "[item=227409] (+10 KP)", evaluator = "flag", params = { quest = 81146 }, note = "Unlock: skill 200" },
					{ label = "[item=227420] (+10 KP)", evaluator = "flag", params = { quest = 81147 }, note = "Unlock: skill 300" },
					{ label = "[item=227431] (+10 KP)", evaluator = "flag", params = { quest = 81148 }, note = "Unlock: skill 400" },
					{ label = "[item=224645] (+10 KP)", evaluator = "flag", params = { quest = 83058 }, note = "Unlock: Renown 12" },
					{ label = "[item=232499] (+10 KP)", evaluator = "flag", params = { quest = 85734 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235865] (+10 KP)", evaluator = "flag", params = { quest = 87255 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224024] (+10 KP)", evaluator = "flag", params = { quest = 82633 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-alchemy-tww", rev = 1,
				name = "Weekly Alchemy The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Alchemy in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_alchemy",
				scope = "perchar",
				require = { profession = 171 },
				steps = {
					{ label = "[item=222546] (+1 KP)", evaluator = "flag", params = { quest = 83725 }, resets = "weekly" },
					{ label = "[item=228773] (+2 KP)", evaluator = "flag", params = { quest = 84133 }, resets = "weekly" },
					{ label = "[item=225234] (+2 KP)", evaluator = "flag", params = { quest = 83253 }, resets = "weekly" },
					{ label = "[item=225235] (+2 KP)", evaluator = "flag", params = { quest = 83255 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3057, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-blacksmithing-tww", rev = 1,
				name = "One-Time Blacksmithing The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Blacksmithing in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_blacksmithing",
				scope = "perchar",
				require = { profession = 164 },
				steps = {
					{ label = "[item=226276] (+3 KP)", evaluator = "flag", params = { quest = 83848 } },
					{ label = "[item=226277] (+3 KP)", evaluator = "flag", params = { quest = 83849 } },
					{ label = "[item=226278] (+3 KP)", evaluator = "flag", params = { quest = 83850 } },
					{ label = "[item=226279] (+3 KP)", evaluator = "flag", params = { quest = 83851 } },
					{ label = "[item=226280] (+3 KP)", evaluator = "flag", params = { quest = 83852 } },
					{ label = "[item=226281] (+3 KP)", evaluator = "flag", params = { quest = 83853 } },
					{ label = "[item=226282] (+3 KP)", evaluator = "flag", params = { quest = 83854 } },
					{ label = "[item=226283] (+3 KP)", evaluator = "flag", params = { quest = 83855 } },
					{ label = "[item=227407] (+10 KP)", evaluator = "flag", params = { quest = 84226 }, note = "Unlock: skill 200" },
					{ label = "[item=227418] (+10 KP)", evaluator = "flag", params = { quest = 84227 }, note = "Unlock: skill 300" },
					{ label = "[item=227429] (+10 KP)", evaluator = "flag", params = { quest = 84228 }, note = "Unlock: skill 400" },
					{ label = "[item=224647] (+10 KP)", evaluator = "flag", params = { quest = 83059 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=232500] (+10 KP)", evaluator = "flag", params = { quest = 85735 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235864] (+10 KP)", evaluator = "flag", params = { quest = 87266 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224038] (+10 KP)", evaluator = "flag", params = { quest = 82631 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-blacksmithing-tww", rev = 1,
				name = "Weekly Blacksmithing The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Blacksmithing in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_blacksmithing",
				scope = "perchar",
				require = { profession = 164 },
				steps = {
					{ label = "[item=222554] (+1 KP)", evaluator = "flag", params = { quest = 83726 }, resets = "weekly" },
					{ label = "[item=228774] (+2 KP)", evaluator = "flag", params = { quest = 84127 }, resets = "weekly" },
					{ label = "[item=225233] (+1 KP)", evaluator = "flag", params = { quest = 83256 }, resets = "weekly" },
					{ label = "[item=225232] (+1 KP)", evaluator = "flag", params = { quest = 83257 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3058, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-enchanting-tww", rev = 1,
				name = "One-Time Enchanting The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Enchanting in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_enchanting",
				scope = "perchar",
				require = { profession = 333 },
				steps = {
					{ label = "[item=226284] (+3 KP)", evaluator = "flag", params = { quest = 83856 } },
					{ label = "[item=226285] (+3 KP)", evaluator = "flag", params = { quest = 83859 } },
					{ label = "[item=226286] (+3 KP)", evaluator = "flag", params = { quest = 83860 } },
					{ label = "[item=226287] (+3 KP)", evaluator = "flag", params = { quest = 83861 } },
					{ label = "[item=226288] (+3 KP)", evaluator = "flag", params = { quest = 83862 } },
					{ label = "[item=226289] (+3 KP)", evaluator = "flag", params = { quest = 83863 } },
					{ label = "[item=226290] (+3 KP)", evaluator = "flag", params = { quest = 83864 } },
					{ label = "[item=226291] (+3 KP)", evaluator = "flag", params = { quest = 83865 } },
					{ label = "[item=227411] (+10 KP)", evaluator = "flag", params = { quest = 81076 }, note = "Unlock: skill 200" },
					{ label = "[item=227422] (+10 KP)", evaluator = "flag", params = { quest = 81077 }, note = "Unlock: skill 300" },
					{ label = "[item=227433] (+10 KP)", evaluator = "flag", params = { quest = 81078 }, note = "Unlock: skill 400" },
					{ label = "[item=224652] (+10 KP)", evaluator = "flag", params = { quest = 83060 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=232501] (+10 KP)", evaluator = "flag", params = { quest = 85736 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235863] (+10 KP)", evaluator = "flag", params = { quest = 87265 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224050] (+10 KP)", evaluator = "flag", params = { quest = 82635 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-enchanting-tww", rev = 1,
				name = "Weekly Enchanting The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Enchanting in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_enchanting",
				scope = "perchar",
				require = { profession = 333 },
				steps = {
					{ label = "[item=222550] (+1 KP)", evaluator = "flag", params = { quest = 83727 }, resets = "weekly" },
					{ label = "[item=227667] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({84084, 84085, 84086}) }, resets = "weekly" },
					{ label = "[item=227659] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({84290, 84291, 84292, 84293, 84294}) }, resets = "weekly" },
					{ label = "[item=227661] (+4 KP)", evaluator = "flag", params = { quest = 84295 }, resets = "weekly" },
					{ label = "[item=225231] (+1 KP)", evaluator = "flag", params = { quest = 83258 }, resets = "weekly" },
					{ label = "[item=225230] (+1 KP)", evaluator = "flag", params = { quest = 83259 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3059, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-engineering-tww", rev = 1,
				name = "One-Time Engineering The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Engineering in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_engineering",
				scope = "perchar",
				require = { profession = 202 },
				steps = {
					{ label = "[item=226292] (+3 KP)", evaluator = "flag", params = { quest = 83866 } },
					{ label = "[item=226293] (+3 KP)", evaluator = "flag", params = { quest = 83867 } },
					{ label = "[item=226294] (+3 KP)", evaluator = "flag", params = { quest = 83868 } },
					{ label = "[item=226295] (+3 KP)", evaluator = "flag", params = { quest = 83869 } },
					{ label = "[item=226296] (+3 KP)", evaluator = "flag", params = { quest = 83870 } },
					{ label = "[item=226297] (+3 KP)", evaluator = "flag", params = { quest = 83871 } },
					{ label = "[item=226298] (+3 KP)", evaluator = "flag", params = { quest = 83872 } },
					{ label = "[item=226299] (+3 KP)", evaluator = "flag", params = { quest = 83873 } },
					{ label = "[item=227412] (+10 KP)", evaluator = "flag", params = { quest = 84229 }, note = "Unlock: skill 200" },
					{ label = "[item=227423] (+10 KP)", evaluator = "flag", params = { quest = 84230 }, note = "Unlock: skill 300" },
					{ label = "[item=227434] (+10 KP)", evaluator = "flag", params = { quest = 84231 }, note = "Unlock: skill 400" },
					{ label = "[item=224653] (+10 KP)", evaluator = "flag", params = { quest = 83063 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=232507] (+10 KP)", evaluator = "flag", params = { quest = 85737 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235862] (+10 KP)", evaluator = "flag", params = { quest = 87264 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224052] (+10 KP)", evaluator = "flag", params = { quest = 82632 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-engineering-tww", rev = 1,
				name = "Weekly Engineering The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Engineering in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_engineering",
				scope = "perchar",
				require = { profession = 202 },
				steps = {
					{ label = "[item=222621] (+1 KP)", evaluator = "flag", params = { quest = 83728 }, resets = "weekly" },
					{ label = "[item=228775] (+1 KP)", evaluator = "flag", params = { quest = 84128 }, resets = "weekly" },
					{ label = "[item=225228] (+1 KP)", evaluator = "flag", params = { quest = 83260 }, resets = "weekly" },
					{ label = "[item=225229] (+1 KP)", evaluator = "flag", params = { quest = 83261 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3060, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-herbalism-tww", rev = 1,
				name = "One-Time Herbalism The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Herbalism in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_herbalism",
				scope = "perchar",
				require = { profession = 182 },
				steps = {
					{ label = "[item=226300] (+3 KP)", evaluator = "flag", params = { quest = 83874 } },
					{ label = "[item=226301] (+3 KP)", evaluator = "flag", params = { quest = 83875 } },
					{ label = "[item=226302] (+3 KP)", evaluator = "flag", params = { quest = 83876 } },
					{ label = "[item=226303] (+3 KP)", evaluator = "flag", params = { quest = 83877 } },
					{ label = "[item=226304] (+3 KP)", evaluator = "flag", params = { quest = 83878 } },
					{ label = "[item=226305] (+3 KP)", evaluator = "flag", params = { quest = 83879 } },
					{ label = "[item=226306] (+3 KP)", evaluator = "flag", params = { quest = 83880 } },
					{ label = "[item=226307] (+3 KP)", evaluator = "flag", params = { quest = 83881 } },
					{ label = "[item=227415] (+15 KP)", evaluator = "flag", params = { quest = 81422 }, note = "Unlock: skill 200" },
					{ label = "[item=227426] (+15 KP)", evaluator = "flag", params = { quest = 81423 }, note = "Unlock: skill 300" },
					{ label = "[item=227437] (+15 KP)", evaluator = "flag", params = { quest = 81424 }, note = "Unlock: skill 400; skill 50" },
					{ label = "[item=224656] (+10 KP)", evaluator = "flag", params = { quest = 83066 }, note = "Unlock: Renown 14; skill 50" },
					{ label = "[item=232503] (+10 KP)", evaluator = "flag", params = { quest = 85738 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235861] (+10 KP)", evaluator = "flag", params = { quest = 87263 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224023] (+10 KP)", evaluator = "flag", params = { quest = 82630 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-herbalism-tww", rev = 1,
				name = "Weekly Herbalism The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Herbalism in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_herbalism",
				scope = "perchar",
				require = { profession = 182 },
				steps = {
					{ label = "[item=222552] (+1 KP)", evaluator = "flag", params = { quest = 83729 }, resets = "weekly" },
					{ label = "[item=224817] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({82970, 82958, 82965, 82916, 82962}) }, resets = "weekly" },
					{ label = "[item=224264] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({81416, 81417, 81418, 81419, 81420}) }, resets = "weekly" },
					{ label = "[item=224265] (+4 KP)", evaluator = "flag", params = { quest = 81421 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3061, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-inscription-tww", rev = 1,
				name = "One-Time Inscription The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Inscription in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_inscription",
				scope = "perchar",
				require = { profession = 773 },
				steps = {
					{ label = "[item=226308] (+3 KP)", evaluator = "flag", params = { quest = 83882 } },
					{ label = "[item=226309] (+3 KP)", evaluator = "flag", params = { quest = 83883 } },
					{ label = "[item=226310] (+3 KP)", evaluator = "flag", params = { quest = 83884 } },
					{ label = "[item=226311] (+3 KP)", evaluator = "flag", params = { quest = 83885 } },
					{ label = "[item=226312] (+3 KP)", evaluator = "flag", params = { quest = 83886 } },
					{ label = "[item=226313] (+3 KP)", evaluator = "flag", params = { quest = 83887 } },
					{ label = "[item=226314] (+3 KP)", evaluator = "flag", params = { quest = 83888 } },
					{ label = "[item=226315] (+3 KP)", evaluator = "flag", params = { quest = 83889 } },
					{ label = "[item=227408] (+10 KP)", evaluator = "flag", params = { quest = 80749 }, note = "Unlock: skill 200" },
					{ label = "[item=227419] (+10 KP)", evaluator = "flag", params = { quest = 80750 }, note = "Unlock: skill 300" },
					{ label = "[item=227430] (+10 KP)", evaluator = "flag", params = { quest = 80751 }, note = "Unlock: skill 400" },
					{ label = "[item=224654] (+10 KP)", evaluator = "flag", params = { quest = 83064 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=232508] (+10 KP)", evaluator = "flag", params = { quest = 85739 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235860] (+10 KP)", evaluator = "flag", params = { quest = 87262 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224053] (+10 KP)", evaluator = "flag", params = { quest = 82636 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-inscription-tww", rev = 1,
				name = "Weekly Inscription The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Inscription in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_inscription",
				scope = "perchar",
				require = { profession = 773 },
				steps = {
					{ label = "[item=222548] (+1 KP)", evaluator = "flag", params = { quest = 83730 }, resets = "weekly" },
					{ label = "[item=228776] (+2 KP)", evaluator = "flag", params = { quest = 84129 }, resets = "weekly" },
					{ label = "[item=225227] (+2 KP)", evaluator = "flag", params = { quest = 83262 }, resets = "weekly" },
					{ label = "[item=225226] (+2 KP)", evaluator = "flag", params = { quest = 83264 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3062, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-jewelcrafting-tww", rev = 1,
				name = "One-Time Jewelcrafting The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Jewelcrafting in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_jewelcrafting",
				scope = "perchar",
				require = { profession = 755 },
				steps = {
					{ label = "[item=226316] (+3 KP)", evaluator = "flag", params = { quest = 83890 } },
					{ label = "[item=226317] (+3 KP)", evaluator = "flag", params = { quest = 83891 } },
					{ label = "[item=226318] (+3 KP)", evaluator = "flag", params = { quest = 83892 } },
					{ label = "[item=226319] (+3 KP)", evaluator = "flag", params = { quest = 83893 } },
					{ label = "[item=226320] (+3 KP)", evaluator = "flag", params = { quest = 83894 } },
					{ label = "[item=226321] (+3 KP)", evaluator = "flag", params = { quest = 83895 } },
					{ label = "[item=226322] (+3 KP)", evaluator = "flag", params = { quest = 83896 } },
					{ label = "[item=226323] (+3 KP)", evaluator = "flag", params = { quest = 83897 } },
					{ label = "[item=227413] (+10 KP)", evaluator = "flag", params = { quest = 81259 }, note = "Unlock: skill 200" },
					{ label = "[item=227424] (+10 KP)", evaluator = "flag", params = { quest = 81260 }, note = "Unlock: skill 300" },
					{ label = "[item=227435] (+10 KP)", evaluator = "flag", params = { quest = 81261 }, note = "Unlock: skill 400" },
					{ label = "[item=224655] (+10 KP)", evaluator = "flag", params = { quest = 83065 }, note = "Unlock: Renown 14; skill 50" },
					{ label = "[item=232504] (+10 KP)", evaluator = "flag", params = { quest = 85740 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235859] (+10 KP)", evaluator = "flag", params = { quest = 87261 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224054] (+10 KP)", evaluator = "flag", params = { quest = 82637 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-jewelcrafting-tww", rev = 1,
				name = "Weekly Jewelcrafting The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Jewelcrafting in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_jewelcrafting",
				scope = "perchar",
				require = { profession = 755 },
				steps = {
					{ label = "[item=222551] (+1 KP)", evaluator = "flag", params = { quest = 83731 }, resets = "weekly" },
					{ label = "[item=228777] (+2 KP)", evaluator = "flag", params = { quest = 84130 }, resets = "weekly" },
					{ label = "[item=225224] (+2 KP)", evaluator = "flag", params = { quest = 83265 }, resets = "weekly" },
					{ label = "[item=225225] (+2 KP)", evaluator = "flag", params = { quest = 83266 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3063, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-leatherworking-tww", rev = 1,
				name = "One-Time Leatherworking The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Leatherworking in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_leatherworking",
				scope = "perchar",
				require = { profession = 165 },
				steps = {
					{ label = "[item=226324] (+3 KP)", evaluator = "flag", params = { quest = 83898 } },
					{ label = "[item=226325] (+3 KP)", evaluator = "flag", params = { quest = 83899 } },
					{ label = "[item=226326] (+3 KP)", evaluator = "flag", params = { quest = 83900 } },
					{ label = "[item=226327] (+3 KP)", evaluator = "flag", params = { quest = 83901 } },
					{ label = "[item=226328] (+3 KP)", evaluator = "flag", params = { quest = 83902 } },
					{ label = "[item=226329] (+3 KP)", evaluator = "flag", params = { quest = 83903 } },
					{ label = "[item=226330] (+3 KP)", evaluator = "flag", params = { quest = 83904 } },
					{ label = "[item=226331] (+3 KP)", evaluator = "flag", params = { quest = 83905 } },
					{ label = "[item=227414] (+10 KP)", evaluator = "flag", params = { quest = 80978 }, note = "Unlock: skill 200" },
					{ label = "[item=227425] (+10 KP)", evaluator = "flag", params = { quest = 80979 }, note = "Unlock: skill 300" },
					{ label = "[item=227436] (+10 KP)", evaluator = "flag", params = { quest = 80980 }, note = "Unlock: skill 400" },
					{ label = "[item=224658] (+10 KP)", evaluator = "flag", params = { quest = 83068 }, note = "Unlock: Renown 14; skill 50" },
					{ label = "[item=232505] (+10 KP)", evaluator = "flag", params = { quest = 85741 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235858] (+10 KP)", evaluator = "flag", params = { quest = 87260 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224056] (+10 KP)", evaluator = "flag", params = { quest = 82626 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-leatherworking-tww", rev = 1,
				name = "Weekly Leatherworking The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Leatherworking in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_leatherworking",
				scope = "perchar",
				require = { profession = 165 },
				steps = {
					{ label = "[item=222549] (+1 KP)", evaluator = "flag", params = { quest = 83732 }, resets = "weekly" },
					{ label = "[item=228778] (+2 KP)", evaluator = "flag", params = { quest = 84131 }, resets = "weekly" },
					{ label = "[item=225223] (+1 KP)", evaluator = "flag", params = { quest = 83267 }, resets = "weekly" },
					{ label = "[item=225222] (+1 KP)", evaluator = "flag", params = { quest = 83268 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3064, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-mining-tww", rev = 1,
				name = "One-Time Mining The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Mining in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_mining",
				scope = "perchar",
				require = { profession = 186 },
				steps = {
					{ label = "[item=226332] (+3 KP)", evaluator = "flag", params = { quest = 83906 } },
					{ label = "[item=226333] (+3 KP)", evaluator = "flag", params = { quest = 83907 } },
					{ label = "[item=226334] (+3 KP)", evaluator = "flag", params = { quest = 83908 } },
					{ label = "[item=226335] (+3 KP)", evaluator = "flag", params = { quest = 83909 } },
					{ label = "[item=226336] (+3 KP)", evaluator = "flag", params = { quest = 83910 } },
					{ label = "[item=226337] (+3 KP)", evaluator = "flag", params = { quest = 83911 } },
					{ label = "[item=226338] (+3 KP)", evaluator = "flag", params = { quest = 83912 } },
					{ label = "[item=226339] (+3 KP)", evaluator = "flag", params = { quest = 83913 } },
					{ label = "[item=227416] (+15 KP)", evaluator = "flag", params = { quest = 81390 }, note = "Unlock: skill 200" },
					{ label = "[item=227427] (+15 KP)", evaluator = "flag", params = { quest = 81391 }, note = "Unlock: skill 300" },
					{ label = "[item=227438] (+15 KP)", evaluator = "flag", params = { quest = 81392 }, note = "Unlock: skill 400" },
					{ label = "[item=224651] (+10 KP)", evaluator = "flag", params = { quest = 83062 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=232509] (+10 KP)", evaluator = "flag", params = { quest = 85742 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235857] (+10 KP)", evaluator = "flag", params = { quest = 87259 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224055] (+10 KP)", evaluator = "flag", params = { quest = 82614 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-mining-tww", rev = 1,
				name = "Weekly Mining The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Mining in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_mining",
				scope = "perchar",
				require = { profession = 186 },
				steps = {
					{ label = "[item=224818] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({83104, 83105, 83103, 83106, 83102}) }, resets = "weekly" },
					{ label = "[item=222553] (+1 KP)", evaluator = "flag", params = { quest = 83733 }, resets = "weekly" },
					{ label = "[item=224583] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({83050, 83051, 83052, 83053, 83054}) }, resets = "weekly" },
					{ label = "[item=224584] (+3 KP)", evaluator = "flag", params = { quest = 83049 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3065, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-skinning-tww", rev = 1,
				name = "One-Time Skinning The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Skinning in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_skinning",
				scope = "perchar",
				require = { profession = 393 },
				steps = {
					{ label = "[item=226340] (+3 KP)", evaluator = "flag", params = { quest = 83914 } },
					{ label = "[item=226341] (+3 KP)", evaluator = "flag", params = { quest = 83915 } },
					{ label = "[item=226342] (+3 KP)", evaluator = "flag", params = { quest = 83916 } },
					{ label = "[item=226343] (+3 KP)", evaluator = "flag", params = { quest = 83917 } },
					{ label = "[item=226344] (+3 KP)", evaluator = "flag", params = { quest = 83918 } },
					{ label = "[item=226345] (+3 KP)", evaluator = "flag", params = { quest = 83919 } },
					{ label = "[item=226346] (+3 KP)", evaluator = "flag", params = { quest = 83920 } },
					{ label = "[item=226347] (+3 KP)", evaluator = "flag", params = { quest = 83921 } },
					{ label = "[item=227417] (+15 KP)", evaluator = "flag", params = { quest = 84232 }, note = "Unlock: skill 200" },
					{ label = "[item=227428] (+15 KP)", evaluator = "flag", params = { quest = 84233 }, note = "Unlock: skill 300" },
					{ label = "[item=227439] (+15 KP)", evaluator = "flag", params = { quest = 84234 }, note = "Unlock: skill 400" },
					{ label = "[item=224657] (+10 KP)", evaluator = "flag", params = { quest = 83067 }, note = "Unlock: Renown 14; skill 50" },
					{ label = "[item=232506] (+10 KP)", evaluator = "flag", params = { quest = 85744 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235856] (+10 KP)", evaluator = "flag", params = { quest = 87258 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224007] (+10 KP)", evaluator = "flag", params = { quest = 82596 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-skinning-tww", rev = 1,
				name = "Weekly Skinning The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Skinning in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_skinning",
				scope = "perchar",
				require = { profession = 393 },
				steps = {
					{ label = "[item=224807] (+3 KP)", evaluator = "group", params = { need = 1, of = flags({83097, 83098, 83100, 82992, 82993}) }, resets = "weekly" },
					{ label = "[item=222649] (+1 KP)", evaluator = "flag", params = { quest = 83734 }, resets = "weekly" },
					{ label = "[item=224780] (+1 KP each, collect 5)", evaluator = "group", params = { need = 5, of = flags({81459, 81460, 81461, 81462, 81463}) }, resets = "weekly" },
					{ label = "[item=224781] (+2 KP)", evaluator = "flag", params = { quest = 81464 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3066, cap = true } },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-onetime-tailoring-tww", rev = 1,
				name = "One-Time Tailoring The War Within Treasures",
				category = "Professions",
				desc = "One-time Knowledge Point sources for Tailoring in The War Within -- world treasures, research books, and first-time gathers. Each is earned once per character.",
				icon = "ui_profession_tailoring",
				scope = "perchar",
				require = { profession = 197 },
				steps = {
					{ label = "[item=226348] (+3 KP)", evaluator = "flag", params = { quest = 83922 } },
					{ label = "[item=226349] (+3 KP)", evaluator = "flag", params = { quest = 83923 } },
					{ label = "[item=226350] (+3 KP)", evaluator = "flag", params = { quest = 83924 } },
					{ label = "[item=226351] (+3 KP)", evaluator = "flag", params = { quest = 83925 } },
					{ label = "[item=226352] (+3 KP)", evaluator = "flag", params = { quest = 83926 } },
					{ label = "[item=226353] (+3 KP)", evaluator = "flag", params = { quest = 83927 } },
					{ label = "[item=226354] (+3 KP)", evaluator = "flag", params = { quest = 83928 } },
					{ label = "[item=226355] (+3 KP)", evaluator = "flag", params = { quest = 83929 } },
					{ label = "[item=227410] (+10 KP)", evaluator = "flag", params = { quest = 80871 }, note = "Unlock: skill 200" },
					{ label = "[item=227421] (+10 KP)", evaluator = "flag", params = { quest = 80872 }, note = "Unlock: skill 300" },
					{ label = "[item=227432] (+10 KP)", evaluator = "flag", params = { quest = 80873 }, note = "Unlock: skill 400" },
					{ label = "[item=224648] (+10 KP)", evaluator = "flag", params = { quest = 83061 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=232502] (+10 KP)", evaluator = "flag", params = { quest = 85745 }, note = "Unlock: Renown 16; skill 50" },
					{ label = "[item=235855] (+10 KP)", evaluator = "flag", params = { quest = 87257 }, note = "Unlock: Renown 12; skill 50" },
					{ label = "[item=224036] (+10 KP)", evaluator = "flag", params = { quest = 82634 }, note = "Unlock: 565x [currency=3056]" },
				},
			},
		},
		{
			bucket = "professions", tag = "The War Within",
			goal = {
				v = 1, id = "tiw:prof-kp-weekly-tailoring-tww", rev = 1,
				name = "Weekly Tailoring The War Within KP",
				category = "Professions",
				desc = "Weekly Knowledge Point sources for Tailoring in The War Within -- treatise, work-order quest, gathered drops, and catch-up currency. Resets each week.",
				icon = "ui_profession_tailoring",
				scope = "perchar",
				require = { profession = 197 },
				steps = {
					{ label = "[item=222547] (+1 KP)", evaluator = "flag", params = { quest = 83735 }, resets = "weekly" },
					{ label = "[item=228779] (+2 KP)", evaluator = "flag", params = { quest = 84132 }, resets = "weekly" },
					{ label = "[item=225221] (+1 KP)", evaluator = "flag", params = { quest = 83269 }, resets = "weekly" },
					{ label = "[item=225220] (+1 KP)", evaluator = "flag", params = { quest = 83270 }, resets = "weekly" },
					{ label = "Catch-up Knowledge", evaluator = "currency", params = { currency = 3067, cap = true } },
				},
			},
		},
	}
end

return ns
